---
- name: Install curl for worker retire | concourse
  package:
    name: curl
    state: present

- name: create work directory | concourse
  file:
    path: "{{ concourse_work_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  become: yes
  become_user: root

- name: create worker launch script | concourse
  template:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: 0700
    force: yes
  become: yes
  become_user: root
  with_items:
    - src: concourse-worker.j2
      dest: "{{ concourse_worker_launcher_path }}"
    - src: concourse-retire-worker.j2
      dest: "{{ concourse_retire_worker_path }}"
    - src: concourse-worker-watchdog.j2
      dest: "{{ concourse_install_dir }}/concourse-worker-watchdog"
    - src: concourse-worker-cleaner.j2
      dest: "{{ concourse_worker_cleaner_path }}"
  notify:
  - restart concourse worker

- name: create worker service | concourse
  template:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    owner: root
    force: yes
  become: yes
  become_user: root
  with_items:
  - src: concourse-worker.service.j2
    dest: /etc/systemd/system/concourse-worker.service
  - src: concourse-worker-watchdog.service.j2
    dest: /etc/systemd/system/concourse-worker-watchdog.service
  - src: concourse-worker-cleaner.service.j2
    dest: /etc/systemd/system/concourse-worker-cleaner.service
  notify:
  - restart concourse worker
