- name: configure web service | concourse
  service:
    name: concourse-web
    enabled: "{{ concourse_service_enabled }}"
  become: yes
  when: concourse_web

- name: configure worker service | concourse
  service:
    name: concourse-worker
    enabled: "{{ concourse_service_enabled }}"
  become: yes
  when: concourse_worker

- name: start web service | concourse
  service:
    name: concourse-web
    state: started
  become: yes
  when: concourse_web and concourse_service_enabled

- name: start worker service | concourse
  service:
    name: concourse-worker
    state: started
  become: yes
  when: concourse_worker and concourse_service_enabled
