---
- name: stop concourse web
  service:
    name: concourse-web
    state: stopped
  become: yes
  when: concourse_web

- name: stop concourse worker
  service:
    name: concourse-worker
    state: stopped
  become: yes
  when: concourse_worker

- name: restart concourse web
  service:
    name: concourse-web
    state: restarted
    enabled: yes
  become: yes
  become_user: root
  when: concourse_web and concourse_service_enabled and concourse_service_start

- name: restart concourse worker
  service:
    name: concourse-worker
    state: restarted
    enabled: yes
  become: yes
  become_user: root
  when: concourse_worker and concourse_service_enabled and concourse_service_start
